//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accion
    {
        public Accion()
        {
            this.Transaccion_Log = new HashSet<Transaccion_Log>();
        }
    
        public byte IDAccion { get; set; }
        public string DescripAccion { get; set; }
    
        public virtual ICollection<Transaccion_Log> Transaccion_Log { get; set; }
    }
}
