//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessPartner
    {
        public int IDUsuario { get; set; }
        public int IDInvitado { get; set; }
        public bool Aceptado { get; set; }
        public Nullable<int> ValoracionUsuario { get; set; }
        public Nullable<int> ValoracionInvitado { get; set; }
        public Nullable<System.DateTime> FechaInvitacion { get; set; }
        public Nullable<System.DateTime> FechaAceptacion { get; set; }
        public Nullable<bool> RelacionPublicaUsuario { get; set; }
        public Nullable<bool> RelacionPublicaInvitado { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
