//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogo
    {
        public Catalogo()
        {
            this.Cart = new HashSet<Cart>();
            this.OrderDetail = new HashSet<OrderDetail>();
            this.WallCartStory = new HashSet<WallCartStory>();
        }
    
        public int IDCatalogo { get; set; }
        public int IDUsuario { get; set; }
        public Nullable<int> IDSubFamilia { get; set; }
        public byte IDUnidadMedida { get; set; }
        public string Referencia { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<short> Plazo { get; set; }
        public Nullable<bool> Mostrar { get; set; }
        public string Keywords { get; set; }
        public Nullable<decimal> ShippingCosts { get; set; }
        public Nullable<decimal> StrikeoutPrice { get; set; }
    
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual SubFamilia SubFamilia { get; set; }
        public virtual Unidad_Medida Unidad_Medida { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual ICollection<WallCartStory> WallCartStory { get; set; }
    }
}
