//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.StuffCustomFolder = new HashSet<StuffCustomFolder>();
            this.WallStory = new HashSet<WallStory>();
        }
    
        public int CategoryID { get; set; }
        public string Description_en { get; set; }
        public string Description_es { get; set; }
        public string Keywords { get; set; }
        public string Autokeywords { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> OrderLanding_en { get; set; }
        public Nullable<int> OrderLanding_es { get; set; }
        public string IcoPath { get; set; }
        public Nullable<int> OrderMenu_en { get; set; }
        public Nullable<int> OrderMenu_es { get; set; }
    
        public virtual ICollection<StuffCustomFolder> StuffCustomFolder { get; set; }
        public virtual ICollection<WallStory> WallStory { get; set; }
    }
}
