//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public Comments()
        {
            this.Comments1 = new HashSet<Comments>();
        }
    
        public int IDComments { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Comentario { get; set; }
        public int IDUsuario { get; set; }
        public Nullable<int> IDParentComment { get; set; }
    
        public virtual ICollection<Comments> Comments1 { get; set; }
        public virtual Comments Comments2 { get; set; }
        public virtual User User { get; set; }
    }
}
