//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.User = new HashSet<User>();
        }
    
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string CommercialName { get; set; }
        public string EIN { get; set; }
        public string WEB { get; set; }
        public string MobilePhone { get; set; }
        public string Phone { get; set; }
        public string Skype { get; set; }
        public string LinkedIn { get; set; }
        public string Address { get; set; }
        public string Complement { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIPCode { get; set; }
        public short CountryID { get; set; }
        public string Resource { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        public byte[] Logo { get; set; }
    
        public virtual Pais Pais { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
