//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuraciones
    {
        public Configuraciones()
        {
            this.Portales = new HashSet<Portales>();
            this.PropiedadesConfiguracion = new HashSet<PropiedadesConfiguracion>();
        }
    
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int IdConfiguraciones { get; set; }
    
        public virtual ICollection<Portales> Portales { get; set; }
        public virtual ICollection<PropiedadesConfiguracion> PropiedadesConfiguracion { get; set; }
    }
}
