//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorScrapper
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public bool ErrorBrand { get; set; }
        public bool ErrorModel { get; set; }
        public bool ErrorName { get; set; }
        public bool ErrorPrice { get; set; }
        public bool ErrorImages { get; set; }
    }
}
