//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familia
    {
        public Familia()
        {
            this.SubFamilia = new HashSet<SubFamilia>();
        }
    
        public int IDFamilia { get; set; }
        public int IDLineaNegocio { get; set; }
        public string DescripFamilia { get; set; }
    
        public virtual Linea_Negocio Linea_Negocio { get; set; }
        public virtual ICollection<SubFamilia> SubFamilia { get; set; }
    }
}
