//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiltrosUsuario
    {
        public int Id { get; set; }
        public int Id_Usuario { get; set; }
        public string Descripcion { get; set; }
        public string Pantalla { get; set; }
        public string ObjetoPantalla { get; set; }
        public string Filtro { get; set; }
    
        public virtual User User { get; set; }
    }
}
