//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Followers
    {
        public int IDFollow { get; set; }
        public int IDFollower { get; set; }
        public int IDFollowed { get; set; }
        public System.DateTime FollowDate { get; set; }
        public bool PublicFollow { get; set; }
        public bool Active { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
