//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender
    {
        public Gender()
        {
            this.User = new HashSet<User>();
            this.WallStory_Gender = new HashSet<WallStory_Gender>();
        }
    
        public string GenderId { get; set; }
        public string Description_en { get; set; }
        public string Description_es { get; set; }
        public string Keywords { get; set; }
    
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<WallStory_Gender> WallStory_Gender { get; set; }
    }
}
