//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idioma
    {
        public Idioma()
        {
            this.User = new HashSet<User>();
        }
    
        public string IDIdioma { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<User> User { get; set; }
    }
}
