//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabEntities : DbContext
    {
        public LabEntities()
            : base("name=LabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Accion> Accion { get; set; }
        public DbSet<AgeRank> AgeRank { get; set; }
        public DbSet<Brand> Brand { get; set; }
        public DbSet<BusinessPartner> BusinessPartner { get; set; }
        public DbSet<Cart> Cart { get; set; }
        public DbSet<Catalogo> Catalogo { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<ChatOptions> ChatOptions { get; set; }
        public DbSet<Color> Color { get; set; }
        public DbSet<Comments> Comments { get; set; }
        public DbSet<Company> Company { get; set; }
        public DbSet<CondicionPago> CondicionPago { get; set; }
        public DbSet<Configuraciones> Configuraciones { get; set; }
        public DbSet<ErrorScrapper> ErrorScrapper { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<Familia> Familia { get; set; }
        public DbSet<FiltrosUsuario> FiltrosUsuario { get; set; }
        public DbSet<Followers> Followers { get; set; }
        public DbSet<FormaPago> FormaPago { get; set; }
        public DbSet<Gender> Gender { get; set; }
        public DbSet<Groupon> Groupon { get; set; }
        public DbSet<Idioma> Idioma { get; set; }
        public DbSet<Invite> Invite { get; set; }
        public DbSet<Linea_Negocio> Linea_Negocio { get; set; }
        public DbSet<Mensaje_Archivos> Mensaje_Archivos { get; set; }
        public DbSet<Mensajeria> Mensajeria { get; set; }
        public DbSet<Monedas> Monedas { get; set; }
        public DbSet<Notifications> Notifications { get; set; }
        public DbSet<OnlineStores> OnlineStores { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderDetail> OrderDetail { get; set; }
        public DbSet<OrderStatus> OrderStatus { get; set; }
        public DbSet<Pais> Pais { get; set; }
        public DbSet<Partner> Partner { get; set; }
        public DbSet<PaymentMethod> PaymentMethod { get; set; }
        public DbSet<Portales> Portales { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductType> ProductType { get; set; }
        public DbSet<PropiedadesConfiguracion> PropiedadesConfiguracion { get; set; }
        public DbSet<PropiedadesConfiguracionBase> PropiedadesConfiguracionBase { get; set; }
        public DbSet<Propietario> Propietario { get; set; }
        public DbSet<Pyramid> Pyramid { get; set; }
        public DbSet<RecognizerConfiguration> RecognizerConfiguration { get; set; }
        public DbSet<Season> Season { get; set; }
        public DbSet<SitemapURL> SitemapURL { get; set; }
        public DbSet<Store> Store { get; set; }
        public DbSet<StuffCustomFolder> StuffCustomFolder { get; set; }
        public DbSet<SubFamilia> SubFamilia { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tipo_Transaccion> Tipo_Transaccion { get; set; }
        public DbSet<Transaccion> Transaccion { get; set; }
        public DbSet<Transaccion_Archivos> Transaccion_Archivos { get; set; }
        public DbSet<Transaccion_Articulos> Transaccion_Articulos { get; set; }
        public DbSet<Transaccion_Log> Transaccion_Log { get; set; }
        public DbSet<Transaccion_URLs> Transaccion_URLs { get; set; }
        public DbSet<Tribe> Tribe { get; set; }
        public DbSet<TypeNotifications> TypeNotifications { get; set; }
        public DbSet<Unidad_Medida> Unidad_Medida { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<User_CompanyClassification> User_CompanyClassification { get; set; }
        public DbSet<WallAttachmentStory> WallAttachmentStory { get; set; }
        public DbSet<WallCartStory> WallCartStory { get; set; }
        public DbSet<WallCommentStory> WallCommentStory { get; set; }
        public DbSet<WallControlConfiguration> WallControlConfiguration { get; set; }
        public DbSet<WallInstanceControlConfiguration> WallInstanceControlConfiguration { get; set; }
        public DbSet<WallInstanceControlPropertyConfiguration> WallInstanceControlPropertyConfiguration { get; set; }
        public DbSet<WallLikeStory> WallLikeStory { get; set; }
        public DbSet<WallOwnStory> WallOwnStory { get; set; }
        public DbSet<WallPropertyConfiguration> WallPropertyConfiguration { get; set; }
        public DbSet<WallRebuyStory> WallRebuyStory { get; set; }
        public DbSet<WallRecommendedStory> WallRecommendedStory { get; set; }
        public DbSet<WallRelationControlConfiguration> WallRelationControlConfiguration { get; set; }
        public DbSet<WallRelationStory> WallRelationStory { get; set; }
        public DbSet<WallShareStory> WallShareStory { get; set; }
        public DbSet<WallStories_Result> WallStories_Result { get; set; }
        public DbSet<WallStory> WallStory { get; set; }
        public DbSet<WallStory_Gender> WallStory_Gender { get; set; }
        public DbSet<WallStoryTag> WallStoryTag { get; set; }
        public DbSet<WallTemplateConfiguration> WallTemplateConfiguration { get; set; }
        public DbSet<WallTradeStory> WallTradeStory { get; set; }
        public DbSet<WallTypeStory> WallTypeStory { get; set; }
        public DbSet<WallWishStory> WallWishStory { get; set; }
    }
}
