//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int NotificationId { get; set; }
        public int TypeId { get; set; }
        public int SourceId { get; set; }
        public Nullable<int> SourceParentId { get; set; }
        public int UserId { get; set; }
        public bool Visited { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> NotificationView { get; set; }
    
        public virtual TypeNotifications TypeNotifications { get; set; }
        public virtual User User { get; set; }
        public virtual WallStory WallStory { get; set; }
    }
}
