//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            this.WallTradeStory = new HashSet<WallTradeStory>();
        }
    
        public int OrderDetailID { get; set; }
        public int UserID { get; set; }
        public int UserIDCatalog { get; set; }
        public int CatalogID { get; set; }
        public int Quantity { get; set; }
        public string Reference { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> DeliveryTime { get; set; }
        public int OrderID { get; set; }
    
        public virtual Catalogo Catalogo { get; set; }
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<WallTradeStory> WallTradeStory { get; set; }
    }
}
