//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public int OrderID { get; set; }
        public System.DateTime Date { get; set; }
        public int UserID { get; set; }
        public int PaymentMethodID { get; set; }
        public int OrderStatusID { get; set; }
        public decimal TotalAmount { get; set; }
        public string CurrencyCode { get; set; }
        public decimal ShippingCosts { get; set; }
        public string ShippingComments { get; set; }
        public Nullable<int> EstimatedDelivery { get; set; }
        public string BillingName { get; set; }
        public string BillingLastName { get; set; }
        public string BillingCompany { get; set; }
        public string BillingAddress { get; set; }
        public Nullable<short> BillingCountryID { get; set; }
        public string BillingState { get; set; }
        public string BillingZip { get; set; }
        public string BillingCity { get; set; }
        public string BillingPhoneNumber { get; set; }
        public string BillingEmail { get; set; }
        public string BillingDocument { get; set; }
        public string ShippingName { get; set; }
        public string ShippingLastName { get; set; }
        public string ShippingCompany { get; set; }
        public string ShippingAddress { get; set; }
        public short ShippingCountryID { get; set; }
        public string ShippingState { get; set; }
        public string ShippingZip { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingPhoneNumber { get; set; }
        public string ShippingEmail { get; set; }
        public string GlobalUniqueIdentifier { get; set; }
        public bool Private { get; set; }
    
        public virtual Monedas Monedas { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Pais Pais1 { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}
