//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public Pais()
        {
            this.Company = new HashSet<Company>();
            this.Order = new HashSet<Order>();
            this.Order1 = new HashSet<Order>();
            this.User = new HashSet<User>();
            this.User1 = new HashSet<User>();
        }
    
        public short IDPais { get; set; }
        public string ISO { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string ISO3 { get; set; }
        public Nullable<short> numcode { get; set; }
    
        public virtual ICollection<Company> Company { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Order> Order1 { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<User> User1 { get; set; }
    }
}
