//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int PaymentMethodID { get; set; }
        public string PaymentMethod1 { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
