//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string StoreProductId { get; set; }
        public string Url { get; set; }
        public string ImageUrl { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Category { get; set; }
        public string Department { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string CurrencyCode { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<long> EAN { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<int> StoryId { get; set; }
        public Nullable<bool> isAutoFetched { get; set; }
        public Nullable<int> FetchSource { get; set; }
        public Nullable<int> PublisherThread { get; set; }
        public Nullable<long> UPC { get; set; }
    }
}
