//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropiedadesConfiguracionBase
    {
        public int IdPropiedadesConfiguracionBase { get; set; }
        public string Campo { get; set; }
        public string TagSustituir { get; set; }
        public string Valor { get; set; }
        public string TipoCampo { get; set; }
        public int Orden { get; set; }
        public string Descripcion { get; set; }
    }
}
