//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pyramid
    {
        public Pyramid()
        {
            this.WallStory = new HashSet<WallStory>();
        }
    
        public int PyramidId { get; set; }
        public string Description_en { get; set; }
        public string Description_es { get; set; }
        public string Keywords { get; set; }
    
        public virtual ICollection<WallStory> WallStory { get; set; }
    }
}
