//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int StoreId { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string Region { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime FirstLoadDate { get; set; }
        public Nullable<int> ThirdPartyStoreId { get; set; }
    
        public virtual User User { get; set; }
    }
}
