//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubFamilia
    {
        public SubFamilia()
        {
            this.Catalogo = new HashSet<Catalogo>();
        }
    
        public int IDSubFamilia { get; set; }
        public int IDFamilia { get; set; }
        public string DescripSubFamilia { get; set; }
    
        public virtual ICollection<Catalogo> Catalogo { get; set; }
        public virtual Familia Familia { get; set; }
    }
}
