//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Transaccion
    {
        public Tipo_Transaccion()
        {
            this.Transaccion = new HashSet<Transaccion>();
        }
    
        public short IDTipoTransaccion { get; set; }
        public string DescripTipoTransaccion { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual ICollection<Transaccion> Transaccion { get; set; }
    }
}
