//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public Transaccion()
        {
            this.Transaccion_Archivos = new HashSet<Transaccion_Archivos>();
            this.Transaccion_URLs = new HashSet<Transaccion_URLs>();
            this.Transaccion_Log = new HashSet<Transaccion_Log>();
            this.Transaccion_Articulos = new HashSet<Transaccion_Articulos>();
        }
    
        public int IDTransaccion { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaTransaccion { get; set; }
        public string NumeroTransaccionC { get; set; }
        public string NumeroTransaccionP { get; set; }
        public int IDCliente { get; set; }
        public Nullable<int> IDProveedor { get; set; }
        public string DescripTransaccion { get; set; }
        public byte IDEstado { get; set; }
        public byte IDEstado2 { get; set; }
        public byte IDEstado3 { get; set; }
        public byte IDPropietario { get; set; }
        public byte IDGroupon { get; set; }
        public Nullable<System.DateTime> FechaCierreGroupon { get; set; }
        public string NumeroFactura { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<byte> IDFormaPagoPrevista { get; set; }
        public Nullable<byte> IDCondicionPagoPrevista { get; set; }
        public Nullable<System.DateTime> FechaPagoPrevista { get; set; }
        public Nullable<byte> IDFormaPagoReal { get; set; }
        public Nullable<byte> IDCondicionPagoReal { get; set; }
        public Nullable<System.DateTime> FechaPagoReal { get; set; }
        public Nullable<System.DateTime> FechaAbonoPrevista { get; set; }
        public Nullable<System.DateTime> FechaAbonoReal { get; set; }
        public Nullable<System.DateTime> FechaEntregaPrevista { get; set; }
        public Nullable<System.DateTime> FechaEntregaReal { get; set; }
        public string LugarEntregaPrevisto { get; set; }
        public string LugarEntregaReal { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> Notificacion { get; set; }
        public Nullable<bool> Alarma { get; set; }
        public Nullable<short> Evaluacion { get; set; }
        public short IDTipoTransaccion { get; set; }
        public bool Archivo { get; set; }
        public string CodMoneda { get; set; }
        public Nullable<bool> Publica { get; set; }
        public string TipoTransaccionUsuario { get; set; }
        public Nullable<int> OngoingDeals { get; set; }
        public Nullable<byte> Ambito { get; set; }
    
        public virtual CondicionPago CondicionPago { get; set; }
        public virtual CondicionPago CondicionPago1 { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Estado Estado1 { get; set; }
        public virtual Estado Estado2 { get; set; }
        public virtual FormaPago FormaPago { get; set; }
        public virtual FormaPago FormaPago1 { get; set; }
        public virtual Groupon Groupon { get; set; }
        public virtual Monedas Monedas { get; set; }
        public virtual Propietario Propietario { get; set; }
        public virtual Tipo_Transaccion Tipo_Transaccion { get; set; }
        public virtual ICollection<Transaccion_Archivos> Transaccion_Archivos { get; set; }
        public virtual ICollection<Transaccion_URLs> Transaccion_URLs { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Transaccion_Log> Transaccion_Log { get; set; }
        public virtual ICollection<Transaccion_Articulos> Transaccion_Articulos { get; set; }
    }
}
