//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion_Archivos
    {
        public int IDArchivo { get; set; }
        public int IDTransaccion { get; set; }
        public string Nombre { get; set; }
        public string NombreFisico { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Transaccion Transaccion { get; set; }
    }
}
