//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion_Articulos
    {
        public int IDTransaccionArticulo { get; set; }
        public int IDTransaccion { get; set; }
        public string Referencia { get; set; }
        public string Descripcion { get; set; }
        public decimal CantidadSolicitada { get; set; }
        public Nullable<decimal> CantidadEntregada { get; set; }
        public Nullable<decimal> CantidadFacturada { get; set; }
        public Nullable<decimal> PrecioPedido { get; set; }
        public Nullable<decimal> PrecioEntregada { get; set; }
        public Nullable<decimal> PrecioFactura { get; set; }
        public Nullable<decimal> ImporteTotalPedido { get; set; }
        public Nullable<decimal> ImporteTotalEntregado { get; set; }
        public Nullable<decimal> ImporteTotalFactura { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<bool> Portada { get; set; }
        public string Observaciones { get; set; }
        public string CodMoneda { get; set; }
        public Nullable<byte> IDUnidadMedida { get; set; }
        public Nullable<int> IDCatalogo { get; set; }
        public Nullable<short> Plazo { get; set; }
    
        public virtual Transaccion Transaccion { get; set; }
    }
}
