//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidad_Medida
    {
        public Unidad_Medida()
        {
            this.Catalogo = new HashSet<Catalogo>();
        }
    
        public byte IDUnidadMedida { get; set; }
        public string DescripUnidadMedida { get; set; }
    
        public virtual ICollection<Catalogo> Catalogo { get; set; }
    }
}
