//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_CompanyClassification
    {
        public int ID_Usuario { get; set; }
        public int ID_Clasificacion { get; set; }
        public string Descripcion { get; set; }
    }
}
