//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BusinessPartner = new HashSet<BusinessPartner>();
            this.BusinessPartner1 = new HashSet<BusinessPartner>();
            this.Cart = new HashSet<Cart>();
            this.Catalogo = new HashSet<Catalogo>();
            this.Comments = new HashSet<Comments>();
            this.FiltrosUsuario = new HashSet<FiltrosUsuario>();
            this.Followers = new HashSet<Followers>();
            this.Followers1 = new HashSet<Followers>();
            this.Invite = new HashSet<Invite>();
            this.Mensajeria = new HashSet<Mensajeria>();
            this.Mensajeria1 = new HashSet<Mensajeria>();
            this.Notifications = new HashSet<Notifications>();
            this.OnlineStores = new HashSet<OnlineStores>();
            this.Order = new HashSet<Order>();
            this.OrderDetail = new HashSet<OrderDetail>();
            this.OrderDetail1 = new HashSet<OrderDetail>();
            this.Store = new HashSet<Store>();
            this.StuffCustomFolder = new HashSet<StuffCustomFolder>();
            this.Transaccion = new HashSet<Transaccion>();
            this.Transaccion1 = new HashSet<Transaccion>();
            this.Transaccion_Log = new HashSet<Transaccion_Log>();
            this.User1 = new HashSet<User>();
            this.WallLikeStory = new HashSet<WallLikeStory>();
            this.WallRecommendedStory = new HashSet<WallRecommendedStory>();
            this.WallRelationStory = new HashSet<WallRelationStory>();
            this.WallShareStory = new HashSet<WallShareStory>();
            this.WallStory = new HashSet<WallStory>();
            this.WallWishStory = new HashSet<WallWishStory>();
        }
    
        public int UserID { get; set; }
        public bool Active { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string SSN { get; set; }
        public string GenderId { get; set; }
        public string RelativePath { get; set; }
        public Nullable<bool> PictureChanged { get; set; }
        public string JobTitle { get; set; }
        public string Skype { get; set; }
        public string LinkedIn { get; set; }
        public string MobilePhone { get; set; }
        public string Phone { get; set; }
        public string WEB { get; set; }
        public string Address { get; set; }
        public string Complement { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIPCode { get; set; }
        public short CountryID { get; set; }
        public string LanguageID { get; set; }
        public string CurrencyID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public Nullable<long> UserIDFacebook { get; set; }
        public Nullable<long> UserIDTwitter { get; set; }
        public string EmailFacebook { get; set; }
        public string EmailTwitter { get; set; }
        public byte[] PictureFacebook { get; set; }
        public byte[] PictureTwitter { get; set; }
        public Nullable<bool> AutoPostFacebook { get; set; }
        public Nullable<bool> AutoPostTwitter { get; set; }
        public Nullable<bool> Welcome { get; set; }
        public Nullable<int> InvitePartner { get; set; }
        public Nullable<System.DateTime> LastAccessDate { get; set; }
        public string AboutMe { get; set; }
        public string FavouriteBrands { get; set; }
        public Nullable<System.DateTime> LastReminderSent { get; set; }
        public Nullable<bool> MosaicView { get; set; }
        public string Slug { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<short> ShoppingCountryID { get; set; }
        public Nullable<bool> ReceiveNotification { get; set; }
    
        public virtual ICollection<BusinessPartner> BusinessPartner { get; set; }
        public virtual ICollection<BusinessPartner> BusinessPartner1 { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual ICollection<Catalogo> Catalogo { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<FiltrosUsuario> FiltrosUsuario { get; set; }
        public virtual ICollection<Followers> Followers { get; set; }
        public virtual ICollection<Followers> Followers1 { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Idioma Idioma { get; set; }
        public virtual ICollection<Invite> Invite { get; set; }
        public virtual ICollection<Mensajeria> Mensajeria { get; set; }
        public virtual ICollection<Mensajeria> Mensajeria1 { get; set; }
        public virtual Monedas Monedas { get; set; }
        public virtual ICollection<Notifications> Notifications { get; set; }
        public virtual ICollection<OnlineStores> OnlineStores { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail1 { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Pais Pais1 { get; set; }
        public virtual ICollection<Store> Store { get; set; }
        public virtual ICollection<StuffCustomFolder> StuffCustomFolder { get; set; }
        public virtual ICollection<Transaccion> Transaccion { get; set; }
        public virtual ICollection<Transaccion> Transaccion1 { get; set; }
        public virtual ICollection<Transaccion_Log> Transaccion_Log { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<WallLikeStory> WallLikeStory { get; set; }
        public virtual ICollection<WallRecommendedStory> WallRecommendedStory { get; set; }
        public virtual ICollection<WallRelationStory> WallRelationStory { get; set; }
        public virtual ICollection<WallShareStory> WallShareStory { get; set; }
        public virtual ICollection<WallStory> WallStory { get; set; }
        public virtual ICollection<WallWishStory> WallWishStory { get; set; }
    }
}
