//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WallStory_Gender
    {
        public int StoryId { get; set; }
        public string GenderId { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual WallStory WallStory { get; set; }
        public virtual WallStory_Gender WallStory_Gender1 { get; set; }
        public virtual WallStory_Gender WallStory_Gender2 { get; set; }
    }
}
