//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WallControlConfiguration
    {
        public WallControlConfiguration()
        {
            this.WallInstanceControlConfiguration = new HashSet<WallInstanceControlConfiguration>();
        }
    
        public int WallControlConfigurationId { get; set; }
        public string Name { get; set; }
        public string AssemblyName { get; set; }
    
        public virtual ICollection<WallInstanceControlConfiguration> WallInstanceControlConfiguration { get; set; }
    }
}
