//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WallInstanceControlConfiguration
    {
        public WallInstanceControlConfiguration()
        {
            this.WallInstanceControlPropertyConfiguration = new HashSet<WallInstanceControlPropertyConfiguration>();
            this.WallRelationControlConfiguration = new HashSet<WallRelationControlConfiguration>();
            this.WallRelationControlConfiguration1 = new HashSet<WallRelationControlConfiguration>();
        }
    
        public int WallInstanceControlConfigurationId { get; set; }
        public int WallControlConfigurationId { get; set; }
        public string KeyName { get; set; }
    
        public virtual WallControlConfiguration WallControlConfiguration { get; set; }
        public virtual ICollection<WallInstanceControlPropertyConfiguration> WallInstanceControlPropertyConfiguration { get; set; }
        public virtual ICollection<WallRelationControlConfiguration> WallRelationControlConfiguration { get; set; }
        public virtual ICollection<WallRelationControlConfiguration> WallRelationControlConfiguration1 { get; set; }
    }
}
