//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WallInstanceControlPropertyConfiguration
    {
        public int WallInstanceControlPropertyConfigurationId { get; set; }
        public int WallInstanceControlConfigurationId { get; set; }
        public int WallPropertyConfigurationId { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string Value { get; set; }
    
        public virtual WallInstanceControlConfiguration WallInstanceControlConfiguration { get; set; }
        public virtual WallPropertyConfiguration WallPropertyConfiguration { get; set; }
    }
}
