//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WallPropertyConfiguration
    {
        public WallPropertyConfiguration()
        {
            this.WallInstanceControlPropertyConfiguration = new HashSet<WallInstanceControlPropertyConfiguration>();
        }
    
        public int WallPropertyConfigurationId { get; set; }
        public string Name { get; set; }
        public string IndexProperty { get; set; }
    
        public virtual ICollection<WallInstanceControlPropertyConfiguration> WallInstanceControlPropertyConfiguration { get; set; }
    }
}
