//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WallRelationControlConfiguration
    {
        public int WallRelationInstanceControlConfigurationId { get; set; }
        public int WallContainerControlId { get; set; }
        public int WallInstanceControlId { get; set; }
    
        public virtual WallInstanceControlConfiguration WallInstanceControlConfiguration { get; set; }
        public virtual WallInstanceControlConfiguration WallInstanceControlConfiguration1 { get; set; }
    }
}
