//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WallTradeStory
    {
        public int WallTradeStoryId { get; set; }
        public int StoryId { get; set; }
        public int OrderDetailID { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual WallStory WallStory { get; set; }
    }
}
