//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WallTemplateConfiguration
    {
        public int WallTemplateConfigurationId { get; set; }
        public string KeyName { get; set; }
        public string Template { get; set; }
        public string Language { get; set; }
    }
}
