//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMLaboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WallAttachmentStory
    {
        public int WallAttachmentId { get; set; }
        public int StoryId { get; set; }
        public string Comment { get; set; }
        public string FileName { get; set; }
        public int LengthBytes { get; set; }
        public string MimeType { get; set; }
        public string Folder { get; set; }
        public string AbsoluteUrl { get; set; }
        public string SourceUrl { get; set; }
        public string PhotoUrl { get; set; }
        public string TitlePage { get; set; }
        public string DescriptionPage { get; set; }
        public string KeywordsPage { get; set; }
        public Nullable<byte> MyRating { get; set; }
        public string RelativePath { get; set; }
    
        public virtual WallStory WallStory { get; set; }
    }
}
